---
driver:
  name: docker

driver_config:
  provision_command:
    - apt-get update && apt-get install net-tools
    - curl -L https://www.opscode.com/chef/install.sh | bash -s -- -p -v 12.3.0
    - env GEM_HOME=/tmp/verifier/gems GEM_PATH=/tmp/verifier/gems GEM_CACHE=/tmp/verifier/gems/cache /opt/chef/embedded/bin/gem install thor busser busser-serverspec serverspec bundler && chown -R kitchen:kitchen /tmp/verifier
  require_chef_omnibus: false
  use_sudo: false

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04
