---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.0.3
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus

platforms:
- name: ubuntu-12.04
  driver_config:
    box: chef/ubuntu-12.04-i386
    box_url: https://atlas.hashicorp.com/chef/boxes/ubuntu-12.04-i386/versions/1.0.0/providers/virtualbox.box
    customize:
      memory: 128

suites:
- name: default
  run_list: ["recipe[sample-app]"]
  attributes: {}
